import sys, os, requests
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import get_connection

def create_table(cursor):
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE player_stats (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id NUMBER,
                    game_id NUMBER,
                    pts NUMBER,
                    reb NUMBER,
                    ast NUMBER,
                    stl NUMBER,
                    blk NUMBER,
                    min VARCHAR2(10)
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
    """)

def insert_player_stats(cursor, stats):
    for s in stats:
        player = s.get('player', {})
        game = s.get('game', {})
        try:
            cursor.execute("""
                INSERT INTO player_stats (player_id, game_id, pts, reb, ast, stl, blk, min)
                VALUES (:1, :2, :3, :4, :5, :6, :7, :8)
            """, (
                player.get('id'),
                game.get('id'),
                s.get('pts'),
                s.get('reb'),
                s.get('ast'),
                s.get('stl'),
                s.get('blk'),
                s.get('min')
            ))
        except Exception as e:
            if "ORA-00001" in str(e):
                continue
            else:
                print(f"⚠️ Skipping record due to error: {e}")

def main():
    conn = get_connection()
    cursor = conn.cursor()
    create_table(cursor)
    print("🧱 Player_Stats table ready.")

    headers = {
        "Accept": "application/json",
        "Authorization": "081aceca-0dd3-40f8-a617-bf5ce7212364"  # Replace with your real key
    }

    print("📡 Fetching player stats from API...")
    response = requests.get("https://api.balldontlie.io/v1/stats?per_page=50", headers=headers)
    print("HTTP Status:", response.status_code)
    print("Response text:", response.text[:200])

    if response.status_code != 200:
        print("❌ API request failed.")
        return

    data = response.json()['data']
    insert_player_stats(cursor, data)
    conn.commit()
    print(f"✅ Inserted {len(data)} player stat records into Oracle DB.")

    cursor.close()
    conn.close()

if __name__ == "__main__":
    main()
